#!/usr/bin/env python
import gflags
import logging
import sys

from google.apputils import app

from snmp_exporter.http import start_http_server

FLAGS = gflags.FLAGS

gflags.DEFINE_string('config_file', None, 'Path to config file.')
gflags.DEFINE_boolean('logtostderr', False, 'Log to STDERR instead of file.')
gflags.DEFINE_integer('port', 9116, 'Port to listen for requests.')
gflags.DEFINE_boolean('verbose', False, 'Turn on debug logging.')

gflags.MarkFlagAsRequired('config_file')


def main(argv):
  log_level = logging.DEBUG if FLAGS.verbose else logging.INFO
  log_file = None if FLAGS.logtostderr else '%s.log' % (argv[0])
  log_format = ('%(levelname)s %(asctime)s.%(msecs)06d %(process)d '
                '%(filename)s:%(lineno)d] %(message)s')
  date_format = '%m%d %H:%M:%S'

  logging.basicConfig(level=log_level, filename=log_file, format=log_format,
                      datefmt=date_format)
  logger = logging.getLogger()

  logger.info('snmp_exporter starting.')
  start_http_server(FLAGS.config_file, FLAGS.port)


if __name__ == '__main__':
  app.run()
